inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "lib/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "storage/**/*"
    - "tmp/**/*"
    - "log/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Alias:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SafeNavigationChainLength:
  Max: 3

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*" # Inheriting BaseService without calling super is OK.
    - "app/models/rdv_solidarites_session/**"

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "scripts/*"
    - "spec/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "config/routes.rb"

Layout/LineLength:
  Max: 120

Layout/LineContinuationLeadingSpace:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/HashSyntax:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/InverseOf:
  Exclude:
    - "app/models/participation.rb"

Rails/BulkChangeTable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - "spec/features/**/*"
    - "spec/requests/api/**/*"

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/MessageChain:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/requests/**/*"
    - "spec/features/**/*"

RSpec/ScatteredSetup:
  Exclude:
    - "spec/requests/**/*"

RSpec/MessageSpies:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

Capybara/SpecificActions:
  Enabled: false

Capybara/SpecificMatcher:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false
