import { Modal } from "bootstrap";

class ConfirmModal {
  constructor() {
    this.modalPartial = document.querySelector("#confirm-modal");
    window.Turbo.setConfirmMethod(this.confirm.bind(this));
    this.checkForExternalConfirmLinks();
  }

  checkForExternalConfirmLinks() {
    // Turbo automatically handles confirmation of internal links (those handled by Rails)
    // but by default there's no way to handle confirmation of external links.
    // This code automatically detects external links with a data-turbo-confirm attribute
    // and shows the confirmation modal when they are clicked.
    document.querySelectorAll("[data-turbo-confirm]").forEach((element) => {
      if (element.target !== "_blank") return;

      element.addEventListener("click", (event) => {
        event.preventDefault();
        this.confirm(element.getAttribute("data-turbo-confirm"), element).then(() => {
          this.modal.hide();
        });
      });
    });
  }

  confirm(message, triggerElement) {
    // We use cloneNode to avoid modifying the original modalPartial
    // this allows to avoid issues when showing up multiple modals in a row.
    // More info https://github.com/betagouv/rdv-insertion/pull/2022#discussion_r1608532748
    const modalContent = this.modalPartial.cloneNode(true);

    const sourceLink = this.getSourceLinkFrom(message, triggerElement)

    if (sourceLink.getAttribute("data-turbo-confirm-template")) {
      modalContent.querySelector(".modal-content").innerHTML = sourceLink.getAttribute("data-turbo-confirm-template");
    } else {
      modalContent.querySelector(".modal-title").textContent = message;
      modalContent.querySelector("#custom-body").innerHTML = sourceLink.getAttribute("data-turbo-confirm-text-content") || message;
      modalContent.querySelector("#confirm-button").innerHTML = sourceLink.getAttribute("data-turbo-confirm-text-action") || "Confirmer";
    }

    this.modal = new Modal(modalContent);
    this.modal.show();

    return new Promise((resolve) => {
      modalContent.querySelector("#confirm-button").addEventListener("click", () => {
        resolve(true);
      });
    });
  }

  getSourceLinkFrom(message, triggerElement) {
    if (triggerElement.tagName !== "FORM") return triggerElement;
    
    // When using Turbo, trigger can be a form autogenerated, not the source link 
    // If it is the case we try to find the source link to get the list of data attributes
    const formData = new FormData(triggerElement);
    const serializedParams = new URLSearchParams(formData).toString();
    let pathName = new URL(triggerElement.getAttribute("action")).pathname
    
    if (serializedParams.length > 0) pathName += `?${serializedParams}`;

    return document.querySelector(`a[href="${pathName}"][data-turbo-confirm="${message}"]`);
  }
}

export default ConfirmModal;
