import { Modal } from "bootstrap";

class ConfirmModal {
  constructor() {
    window.Turbo.setConfirmMethod(this.confirm.bind(this));
    this.modalElement = document.querySelector("#confirm-modal");
  }

  confirm(message, triggerElement) {
    // When using Turbo, trigger can be a form autogenerated, not the source link 
    // If it is the case we try to find the source link to get the list of data attributes
    const pathName = new URL(triggerElement.getAttribute("action")).pathname;
    const sourceLink = triggerElement.getAttribute("data-turbo-confirm-text-content") ? triggerElement : document.querySelector(`a[href='${pathName}'][data-turbo-confirm='${message}']`);

    this.modalElement.querySelector(".modal-title").textContent = message;
    this.modalElement.querySelector("#custom-body").innerHTML = sourceLink.getAttribute("data-turbo-confirm-text-content") || message;
    this.modalElement.querySelector("#confirm-button").innerHTML = sourceLink.getAttribute("data-turbo-confirm-text-action") || "Confirmer";

    this.modal = new Modal(this.modalElement);
    this.modal.show();

    return new Promise((resolve) => {
      this.modalElement.querySelector("#confirm-button").addEventListener("click", () => {
        resolve(true);
      });
    });
  }
}

export default ConfirmModal;