<% if ENV["ENVIRONMENT_NAME"] == "production" %>
monitor_webhook_activity_job:
  cron: "0 0-1,6-23 * * 1-5" # Monitor webhooks activity every hour from Monday to Friday except between 1:00 and 6:00
  class: "MonitorWebhookActivityJob"
send_periodic_invites_job:
  cron: "0 14 * * *" # we send recurrent invitations X days after the previous one, at 14:00
  class: "SendPeriodicInvitesJob"
send_invitation_reminders_job:
  cron: "0 11 * * *" # we send reminders once a day, at 11:00
  class: "SendInvitationRemindersJob"
send_convocation_reminders_job:
  cron: "0 10 * * *" # we send reminders once a day, at 10:00
  class: "SendConvocationRemindersJob"
designate_on_watch_developer_job:
  cron: "0 10 * * mon" # we designate an on watch developer once a week, monday at 10:00
  class: "DesignateOnWatchDeveloperJob"
retrieve_and_notify_all_unavailable_creneaux_job:
  cron: "0 01 * * *" # we verify organisations creneaux availability once a day, at 01:00
  class: "Creneaux::RetrieveAndNotifyAllUnavailableCreneauxJob"
<% end %>

upsert_global_stats_job:
  cron: "0 22 * * 6" # we compute global stats once a week, the saturday at 22:00
  class: "Stats::GlobalStats::UpsertStatsJob"
upsert_monthly_stats_job:
  cron: "0 22 * * 7" # we compute monthly stats once a week, the sunday at 22:00
  class: "Stats::MonthlyStats::UpsertStatsJob"
refresh_out_of_date_follow_up_statuses_job:
  cron: "0 21 * * *" # we refresh out of date statuses once a day, at 21:00
  class: "RefreshOutOfDateFollowUpStatusesJob"
store_all_number_of_creneaux_available_job:
  cron: "0 5 * * *" # we refresh out of date statuses once a day, at 21:00
  class: "Creneaux::StoreAllNumberOfCreneauxAvailableJob"
remove_organisation_users_for_expired_archives_job:
  cron: "0 23 * * *" # we remove expired archived users from organisations once a day, at 23:00
  class: "RemoveOrganisationUsersForExpiredArchivesJob"
destroy_old_ressources_job:
  cron: "0 0 * * *" # we destroy inactive users and useless ressources once a day, at 00:00
  class: "DestroyOldRessourcesJob"
