<% if ENV["ENVIRONMENT_NAME"] == "production" %>
monitor_webhook_activity_job:
  cron: "0 0-1,6-23 * * 1-5" # Monitor webhooks activity every hour from Monday to Friday except between 1:00 and 6:00
  class: "MonitorWebhookActivityJob"
notify_jobs_to_retry_on_mattermost_job:
  cron: "30 10 * * *" # we send jobs in the retry_set once a day, at 10:30
  class: "NotifyJobsToRetryOnMattermostJob"
retrieve_and_notify_all_unavailable_creneaux_job:
  cron: "0 01 * * *" # we verify organisations creneaux availability once a day, at 01:00
  class: "Creneaux::RetrieveAndNotifyAllUnavailableCreneauxJob"
<% end %>

<% if ENV["ENVIRONMENT_NAME"] == "production" || ENV["ENVIRONMENT_NAME"] == "demo" %>
send_invitation_reminders_job:
  cron: "0 11 * * *" # we send reminders once a day, at 11:00
  class: "SendInvitationRemindersJob"
send_convocation_reminders_job:
  cron: "0 10 * * *" # we send reminders once a day, at 10:00
  class: "SendConvocationRemindersJob"
<% end %>

# We compute global stats once a week, the saturday at 22:00
upsert_global_stats_job:
  cron: "0 22 * * 6"
  class: "Stats::GlobalStats::UpsertStatsJob"

# We compute monthly stats once a week on Friday at 22:00
# This task takes several hours to run, so we schedule it for the start of the weekend
# to avoid overlapping with the week load
upsert_monthly_stats_job:
  cron: "0 22 * * 5"
  class: "Stats::MonthlyStats::UpsertStatsJob"

refresh_out_of_date_follow_up_statuses_job:
  cron: "0 21 * * *" # we refresh out of date statuses once a day, at 21:00
  class: "RefreshOutOfDateFollowUpStatusesJob"
store_all_number_of_creneaux_available_job:
  cron: "0 5 * * *" # we refresh out of date statuses once a day, at 21:00
  class: "Creneaux::StoreAllNumberOfCreneauxAvailableJob"
remove_organisation_users_for_expired_archives_job:
  cron: "0 23 * * *" # we remove expired archived users from organisations once a day, at 23:00
  class: "RemoveUsersFromOrgsWithOldArchivesJob"
rgpd_cleanup_job:
  cron: "0 0 * * *" # we destroy inactive users and useless resources once a day, at 00:00
  class: "RgpdCleanupJob"
