---
:queues:
  - within_30s
  - within_5min
  - whenever
  # stats and creneaux have specific queues (with low priority) to specify concurrency limits
  - stats
  - creneaux

:limits:
  stats: 2
  creneaux: 1
